# Generated by Django 4.0.5 on 2022-06-10 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_invoice_total_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='hotel_Main_Img',
            new_name='invoice_image',
        ),
    ]
