# Generated by Django 4.0.5 on 2022-06-10 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_hotel_invoice_image_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.invoice'),
            preserve_default=False,
        ),
    ]
