# Generated by Django 4.0.5 on 2022-06-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_invoice_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='finaldb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
